require_relative './alex_command'

# frozen_string_literal: true

EXTENSIONS = %w[md txt].freeze

def paths_to_review(files)
  files.select do |file|
    EXTENSIONS.any? { |pattern| file.end_with?(pattern) }
  end
end

paths = paths_to_review(helper.all_changed_files)

result = AlexCommand.from_paths(paths)

unless result.status.success?
  markdown(<<~MARKDOWN)
## Inconsiderate words review

```sh
#{result.stderr}
```
  MARKDOWN
end
